###################################################################
# Welcome to Non Profit Data Project
# Developed by https://themeix.com
# Version : 1.0.0
###################################################################

# Site settings
title: National Center for Charitable Statistics
description: A demo of the new NCCS data portal.
baseurl: "/nccs" # the subpath of your site, e.g. /blog
url: ""

# Github  Information
github:
  username: UrbanInstitute 
  reponame: nccs


###
### NAVIGATION BAR
###
# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

navbar:
- title: Data
  url: https://urbaninstitute.github.io/nccs/
- title: Projects
  url: projects
- title: Publications
  url: pubs
- title: Tools
  url: https://davidsmale.netlify.app/portfolio
- title: About
  url: about

feed:
  collections:
    posts:
      path: "/index.xml"
