###################################################################
# Welcome to Non Profit Data Project
# Developed by https://themeix.com
# Version : 1.0.0
###################################################################

# Site settings
title: NCCS
description: A demo of the new NCCS data portal.
baseurl: "/nccs-demo" # the subpath of your site, e.g. /blog
url: ""

# Github  Information
github:
  username: lecy 
  reponame: nccs-demo 


###
### NAVIGATION BAR
###
# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

navbar:
- title: Home
  url: index
- title: Projects
  url: projects
- title: Publications
  url: pubs
- title: Blog
  url: blog
- title: About
  url: about

feed:
  collections:
    posts:
      path: "/index.xml"
