###################################################################
# Welcome to Non Profit Data Project
# Developed by https://themeix.com
# Version : 1.0.0
###################################################################

# Site settings
title: The Nonprofit Data Project
description: Information about several grant-funded nonprofit research projects generating new data for the field.
baseurl: "/nonprofitdata" # the subpath of your site, e.g. /blog
url: ""

# Github  Informations
github:
  username: lecy 
  reponame: nccs-demo 
  owner_name: 
  project_title:

###
### NAVIGATION BAR
###
# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

navbar:
- title: Home
  url: index
- title: Projects
  url: projects
- title: Publications
  url: pubs
- title: Blog
  url: blog
- title: About
  url: about

feed:
  collections:
    posts:
      path: "/index.xml"
